AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates an RDS MySql Instance
Parameters:
  MasterUsername:
    Description: Database administration name.
    Type: String
    Default: rdsroot
  MasterUserPassword:
    NoEcho: 'true'
    Description: Database administration password.
    Type: String
    MinLength: '8'
    AllowedPattern: "[a-zA-Z0-9!?]*"
    ConstraintDescription: Must only contain upper and lowercase letters and numbers
  TcpPort:
    Description: Enter RDS Listening TCP Port number.
    Type: Number
    Default: '3306'
  DatabaseName:
    Type: String
Resources:
  MyRDSDBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    Properties:
      AllocatedStorage: "20"
      DBName: !Ref DatabaseName
      DBInstanceClass: db.t2.micro
      DBInstanceIdentifier: !Join ["-",["MyDbInstance",!Ref "AWS::Region"]]
      Engine: MySQL
      MasterUsername: !Ref MasterUsername
      MasterUserPassword: !Ref MasterUserPassword
      Port:
        Ref: TcpPort
      PubliclyAccessible: True
      StorageEncrypted: 'false'
      StorageType: gp2
      AvailabilityZone: !Select [1,!GetAZs ""]
      Tags:
      - Key: Owner
        Value: Abdul Khumaini