AWSTemplateFormatVersion: '2010-09-09'
Description: This stack creates a lambda for s3 trigger

Parameters:
  BucketName:
    Type: String
    Default: 557bucket1

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:*'
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv
            Function: !GetAtt Lambda.Arn
  
  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: 'mynodelambda1'
      Handler: index.handler
      Role: arn:aws:iam::573351626142:role/service-role/mynodelambda-role-cd8ibrmh
      Code: 
        S3Bucket: '558bucket1'
        S3Key: 'code/lambdards.zip'
      Runtime: "nodejs16.x"
      Timeout: 300
      MemorySize: 512
      TracingConfig:
        Mode: Active
  
  S3InvokeLamdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Lambda
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${BucketName}